[package]
name = "advent_of_code_2024"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
gcd = "2.3.0"
hashbag = "0.1.12"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"
reqwest = { version = "0.12.9", features = ["blocking"] }
tqdm = "0.7.0"
